version: '3.7'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../schema_design/db_schema.sql:/var/lib/postgresql/data/db_schema.sql
    env_file:
      - ../.env

  backend:
    build: ../movies_admin/.
    restart: always
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
    env_file:
      - ../.env


  nginx:
    build:
      nginx/.
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_value:/static/
    restart: always
    depends_on:
      - backend


volumes:
  postgres_data:
  static_value:
